### ISSUE TITLE
support paginating responses with an idempotency token member

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy-rs#1013]
It's unclear what the behavior should be. The Rust SDK intentionally has `make_operation()` consume the input when an idempotency token is needed to prevent accidentally creating a new idempotency token.

Should each request have it's own token? 

This doesn't really make sense from an API perspective—idempotency tokens shouldn't be used on read only operations.

**Comment by jdisanti** [comment]
I think that paginated operations aren't going to have idempotency tokens, so this is likely a non-issue.
