### ISSUE TITLE
Move the TLS server implementation based on Hyper into examples folder

### ISSUE THREAD

**Issue by crisidev** [smithy-lang/smithy-rs#1077]
Branch: https://github.com/awslabs/smithy-rs/tree/https-server/rust-runtime/aws-smithy-http-server/src/server

**Comment by jdisanti** [comment]
I think this is done?

**Comment by crisidev** [comment]
Yes, this was done long ago: https://github.com/smithy-lang/smithy-rs/tree/main/examples/pokemon-service-tls. Resolving.
