### ISSUE TITLE
Justify usages of unsafe

### ISSUE THREAD

**Issue by Velfi** [smithy-lang/smithy-rs#1111]
Per the request of an internal security team, we should include rationales alongside our unsafe code that explain why `unsafe` is necessary and why the code is (to the best of our knowledge) safe.

- [x] [smithy-rs/rust-runtime/aws-smithy-http/src/pin_util.rs](https://github.com/awslabs/smithy-rs/blob/main/rust-runtime/aws-smithy-http/src/pin_util.rs)
  - Removed in #1862.
- [x] [ smithy-rs/rust-runtime/aws-smithy-eventstream/src/str_bytes.rs ](https://github.com/awslabs/smithy-rs/blob/1aa59693eed10713dec0f3774a8a25ca271dbf39/rust-runtime/aws-smithy-eventstream/src/str_bytes.rs#L54)
  - This one has an explainer but we should consider noting this invariant on functions that create `StrBytes`
- [x] [smithy-rs/rust-runtime/aws-smithy-eventstream/src/buf/crc.rs ](https://github.com/awslabs/smithy-rs/blob/1aa59693eed10713dec0f3774a8a25ca271dbf39/rust-runtime/aws-smithy-eventstream/src/buf/crc.rs#L123)

**Comment by jdisanti** [comment]
Is it possible to get rid of `pin_mut` entirely?

**Comment by jjant** [comment]
@jdisanti Yes, it's just been removed in #1862.

**Comment by jdisanti** [comment]
Looks like there's just one more to address, actually.
