### ISSUE TITLE
Server protocol tests extras

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy-rs#1164]
The client has suites like [`rest-json-extras.smithy`](https://github.com/awslabs/smithy-rs/blob/25c50a5f0b6ac6b76bd373ad09bcba4841e4d27c/codegen-test/model/rest-json-extras.smithy#L10) that contains extra protocol tests, some of which are upstreamed in the awslabs/smithy repo and will be hosted there in the next Smithy release.

Ideally the server should also pass these suites, and we should put there additional tests we come up with.

Fixed tests should also go there, instead of hot-patching them at runtime [like we currently do](https://github.com/awslabs/smithy-rs/blob/25c50a5f0b6ac6b76bd373ad09bcba4841e4d27c/codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/generators/protocol/ServerProtocolTestGenerator.kt#L679-L679). Advantages:
* We can more easily upstream the fixed test to awslabs/smithy repo since we write Smithy and not Kotlin.
* When we upgrade to the next Smithy release, the broken ones in `ExpectFailing` will fail because they now pass, so we will get alerted and remove the fixed tests from the "extra" suite.

**Comment by david-perez** [comment]
A first test we should add to not regress on #1163 (but to the extras suite, not to `simple.smithy` like the diff below shows):

```diff
diff --git a/codegen-server-test/model/simple.smithy b/codegen-server-test/model/simple.smithy
index 70dee327..2feae1d2 100644
--- a/codegen-server-test/model/simple.smithy
+++ b/codegen-server-test/model/simple.smithy
@@ -63,7 +63,10 @@ resource Service {
         id: "RegisterServiceResponseTest",
         protocol: "aws.protocols#restJson1",
         params: { id: "1", name: "TestService" },
-        body: "{\"id\":\"1\",\"name\":\"TestService\"}",
+        headers: {
+            "Content-Type": "TestService",
+        },
+        body: "{\"id\":\"1\"}",
         code: 200,
     }
 ])
@@ -85,6 +88,9 @@ structure RegisterServiceInputRequest {
 structure RegisterServiceOutputResponse {
     @required
     id: ServiceId,
+
+    @required
+    @httpHeader("Content-Type")
     name: ServiceName,
 }
```

**Comment by david-perez** [comment]
Another one: `httpQueryParams` duplicate query keys behavior: https://github.com/awslabs/smithy/issues/1071

**Comment by drganjoo** [comment]
We can now remove [the only remaining broken test](
https://github.com/smithy-lang/smithy-rs/blob/c45dc122a1fa7a7067d11ec1bffa01576dd94db3/codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/generators/protocol/ServerProtocolTestGenerator.kt#L946) as it has been [fixed upstream](https://github.com/smithy-lang/smithy/pull/1959)

**Comment by david-perez** [comment]
I'm going to close this since I no longer stand by this:

> Fixed tests should also go there, instead of hot-patching them at runtime [like we currently do](https://github.com/awslabs/smithy-rs/blob/25c50a5f0b6ac6b76bd373ad09bcba4841e4d27c/codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/generators/protocol/ServerProtocolTestGenerator.kt#L679-L679)

Now that we have https://github.com/smithy-lang/smithy-rs/pull/3726/, there are no advantages to putting broken protocol tests in the `<protocol>-extras.smithy` models.
