### ISSUE TITLE
Waiters implementation

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy-rs#119]
- [ ] Design/RFC developer experience
- [x] Implement Jmespath Smithy shape traversal (https://github.com/smithy-lang/smithy-rs/pull/3526)
- [ ] Code generate waiters and hook into existing retry strategy

**Comment by jdisanti** [comment]
Implemented in smithy-rs#3595, smithy-rs#3593, smithy-rs#3585, smithy-rs#3571, and smithy-rs#3569.

**Comment by jmklix** [comment]
> Implemented in [smithy-rs#3595](https://github.com/awslabs/smithy-rs/issues/3595), [smithy-rs#3593](https://github.com/awslabs/smithy-rs/issues/3593), [smithy-rs#3585](https://github.com/awslabs/smithy-rs/issues/3585), [smithy-rs#3571](https://github.com/awslabs/smithy-rs/issues/3571), and [smithy-rs#3569](https://github.com/awslabs/smithy-rs/issues/3569).
