### ISSUE TITLE
Validate benchmarks reliability

### ISSUE THREAD

**Issue by crisidev** [smithy-lang/smithy-rs#1239]
Since #1230 we run a benchmark using wrk against `origin/main` and any pull request and calculate the deviation.

We need to validate if the benchmark is reliable when run by the Github action runner. If it is not reliable we can

* Run the benchmark on hardware we own
* Change the benchmark to count instruction instead of using time

**Comment by david-perez** [comment]
I've been keeping an eye on these. Usually the deviation does not go over 50%, but here's a PR in which we had 94% in one message, 16% in the next one https://github.com/awslabs/smithy-rs/pull/1368.

**Comment by david-perez** [comment]
> Change the benchmark to count instruction instead of using time

Instruction count is is a useful metric for a compiler but not for what we're building. We could introduce severe performance degradation without noticeably increasing instruction count (think e.g. replacing a linear-time query string parsing function with a quadratic one).

**Comment by david-perez** [comment]
Closing since benchmarks were removed years ago because of unreliability, we'll use https://github.com/smithy-lang/smithy-rs/issues/214 as the tracking issue to re-add them.
