### ISSUE TITLE
[SQS customization] Checksum validation

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy-rs#147]
Can be disabled with `DisableComputeChecksums`. This may be modeled now?

**Comment by jdisanti** [comment]
No idea if this is still relevant. Adding `retriage` tag.

**Comment by jdisanti** [comment]
I think we determined this isn't necessary since md5 gets compiled into the SDK rather than it being maybe available by name in a VM (e.g., Java's crypto algorithms, where md5 might not exist for FIPS).
