### ISSUE TITLE
Use OpenSSL as an optional crypto provider

### ISSUE THREAD

**Issue by syedriko** [smithy-lang/smithy-rs#1529]
In a FIPS environment, there is a requirement that all crypto operations are delegated to a FIPS-certified crypto module. Some Linux distributions, such as RHEL, ship FIPS-certified OpenSSL. In order for the SDK to be usable in such environment, it should be possible to rely on OpenSSL for all crypto needs.
https://github.com/awslabs/smithy-rs/issues/261 seems to be related.

**Comment by jdisanti** [comment]
Closing in favor of tracking issue #3563.
