### ISSUE TITLE
Verify XML APIs are returning XML with root elements that match the models 

### ISSUE THREAD

**Issue by Velfi** [smithy-lang/smithy-rs#1668]
@jdisanti did some extra [investigative](https://github.com/awslabs/smithy-rs/pull/1665#discussion_r954371345) [work](https://github.com/awslabs/smithy-rs/pull/1665#discussion_r954373006) while reviewing my PR [Add "invalid xml body root" check exemption for S3's `GetObjectAttributes`](https://github.com/awslabs/smithy-rs/pull/1665) and found several other API that may require the same customization:

- `s3#GetBucketLocation`
- `s3#ListObjects`
- `s3#ListObjectVersions`
- `ec2#GetConsoleOutput`

Test these APIs to see if they return XML errors. If they do, apply the same customization from my PR.

**Alternatively,**

Implement [John's suggestion](https://github.com/awslabs/smithy-rs/pull/1665#discussion_r954373006) to use `xmlName` instead of `allowInvalidXmlRoot` and update any buggy operations (don't forget `s3#GetObjectAttributes`)

**Comment by jdisanti** [comment]
This gets especially muddy since some of the S3 operations overlap. For example, making a call to `ListObjectsV2` without a bucket set results in the XML tag name being `ListAllMyBucketsResult` and a list of buckets in the response.

**Comment by jdisanti** [comment]
Errors are also complicated: https://github.com/awslabs/aws-sdk-rust/issues/873

**Comment by rcoh** [comment]
For `ListObjectsV2` (and other S3 operations with bucket) I _think_ the right answer is actually making `bucket` required—`Bucket` is bound as a httpLabel effectively so it it's missing we're really not sending the right request

**Comment by jdisanti** [comment]
I don't see value in keeping this issue open anymore. I think most of the XML root issues have been discovered and fixed at this point.
