### ISSUE TITLE
Add HTTP/S proxy support to `aws-config`

### ISSUE THREAD

**Issue by jdisanti** [smithy-lang/smithy-rs#1741]
Implement built-in support for handling the `HTTP_PROXY` and `HTTPS_PROXY` environment variables that the other SDKs provide (such as Go and the CLI).

Related customer request: https://github.com/awslabs/aws-sdk-rust/issues/169

**Comment by Velfi** [comment]
relevant: https://github.com/tafia/hyper-proxy

**Comment by jdisanti** [comment]
Closing in favor of https://github.com/awslabs/aws-sdk-rust/issues/169
