### ISSUE TITLE
Host a non-`#[doc(hidden)]` Rust documentation for contributors

### ISSUE THREAD

**Issue by hlbarber** [smithy-lang/smithy-rs#1778]
We use `#[doc(hidden)]` extensively in the `rust-runtime` crates to allow for APIs to be public to the code generated code but not public to the general consumer to avoid semver constraints - if somethings `#[doc(hidden)]` we can change its API without the risk of breaking customer code.

This poses a problem for writing documentation for contributors however - docs are not able to point a link to a hosted document which contains API descriptions.

Compiling our own documentation in CI using

```
RUSTDOCFLAGS='-Z unstable-options --document-hidden-items' cargo +nightly doc
```

and then hosting it would remedy this.

In both the hidden and unhidden cases, having a link to the hosted documentation in the [README.md](https://github.com/awslabs/smithy-rs#readme) would be beneficial.

As an additional side effect, we would also be able to catch broken doc links, lints, etc in CI. Running `cargo doc` in `rust-runtime` reveals 3 lints, running `RUSTDOCFLAGS='-Z unstable-options --document-hidden-items' cargo +nightly doc` reveals 50+.

**Comment by Velfi** [comment]
Personally, I'd rather direct contributors to build the docs themselves using those options. I do agree that being able to find broken doc links would be beneficial.
