### ISSUE TITLE
Implement CloudFront presigning

### ISSUE THREAD

**Issue by jdisanti** [smithy-lang/smithy-rs#1800]
This issue tracks implementation of CloudFront presigning.

Corresponding aws-sdk-rust issue: https://github.com/awslabs/aws-sdk-rust/issues/255

**Comment by ajosecueto** [comment]
Waiting for this...

**Comment by Jasperav** [comment]
@jdisanti Any expectations on a release date?

**Comment by jdisanti** [comment]
@Jasperav - No date for this at the moment.

**Comment by jdisanti** [comment]
Tracking in https://github.com/awslabs/aws-sdk-rust/issues/255 now.
