### ISSUE TITLE
Honor the `default` trait

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy-rs#1860]
Neither clients or servers are honoring [the `default` trait](https://awslabs.github.io/smithy/2.0/spec/type-refinement-traits.html#smithy-api-default-trait) from IDL v2. This trait affects serialization behavior of clients and servers.

Note that as far as I know, [awslabs/smithy does not yet provide protocol tests](https://github.com/awslabs/smithy/issues/1452) exercising this trait, so we may have to write our own and contribute them upstream.

**Comment by jdisanti** [comment]
I think only the server needs to implement this. The clients aren't supposed to send the default value since changing the default is not a backwards breaking change.

**Comment by 82marbag** [comment]
PR failing pending more info on https://github.com/awslabs/smithy/issues/1456

**Comment by jdisanti** [comment]
I believe the client does this correctly now.
