### ISSUE TITLE
Real world usage example

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy-rs#209]
Eg, replace Rusoto in `Dynein` with the Rust SDK

**Comment by DavidSouther** [comment]
Does https://github.com/awsdocs/aws-doc-sdk-examples/issues/3780 contain sufficient information for this request?

* actix-web as HTTP server base
* tracing, tracing-subscriber
* metrics via actix-web-prom
* xray comes "for free" when running on EC2
