### ISSUE TITLE
Add a default middleware for generic clients that utilizes SmithyEndpointStage

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy-rs#2194]
Along with this, we should aim to improve the client construction experience to be more like the AWS client experience, ideally supporting `Client::from_conf(...)` where the HTTP connector is supplied from conf

- [ ] http connector settings are generated for smithy clients
- [ ] add `from_conf` to smithy clients
- [ ] make it possible to augment middleware instead of replacing it

**Comment by jdisanti** [comment]
No longer relevant after the orchestrator refactor.
