### ISSUE TITLE
Use `actions-rs` for CI

### ISSUE THREAD

**Issue by jjant** [smithy-lang/smithy-rs#2419]
[`actions-rs`](https://github.com/actions-rs) provides nicer actions like [`actions-rs/clippy-check`](https://github.com/actions-rs/clippy-check) that show clippy lints directly in GH's file diff viewer.

We currently use [`dtolney/rust-toolchain`](https://github.com/dtolnay/rust-toolchain). Part of this task should be to investigate if there are good reasons for _not_ moving.

**Comment by LukeMathWalker** [comment]
`actions-rs` is pretty much unmaintained, with a fair share of security advisories related to the very old version of NodeJS they rely on.
We migrated _away_ from `actions-rs` and I don't think we should go back.
