### ISSUE TITLE
Add support for `s2n-tls`-backed TLS implementations in clients and servers

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy-rs#2446]
[s2n-tls](https://github.com/aws/s2n-tls) is a TLS implementation maintained by AWS, and as such the main (and only?) advantage of adding `s2n-tls`-backed TLS implementations in smithy-rs clients and servers is that we can enjoy first-party support.

**Comment by jdisanti** [comment]
Closing in favor of #3563.
