### ISSUE TITLE
Private type `SigningInstructions` in public interface (`aws-sigv4`)

### ISSUE THREAD

**Issue by jjant** [smithy-lang/smithy-rs#2454]
The private type `SigningInstructions` shows up in the public function [`aws_sigv4::http_request::sign`](https://docs.rs/aws-sigv4/0.54.1/aws_sigv4/http_request/fn.sign.html), we should probably make that type public:

https://github.com/awslabs/smithy-rs/blob/358d13a09ac40cf13c97d6804644507c244c2134/aws/rust-runtime/aws-sigv4/src/http_request/mod.rs#L59

**Comment by jdisanti** [comment]
Looks like this was fixed at some point.
