### ISSUE TITLE
Update Pokémon Service to use Smithy IDL v2

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy-rs#2523]
Smithy IDL v2 has long been released and there's good support for it in the server generator. Our example Pokémon Service should reflect standard best practices; we should give a good example and use the latest IDL.

**Comment by timClicks** [comment]
We should also add some complexity to the service to demonstrate some more features.

**Comment by david-perez** [comment]
@timClicks What things did you have in mind? We showcase pretty much everything we support: TLS, Lambda integration, data and event streaming, usual request-reply operations, sensitive data...
