### ISSUE TITLE
Integrate `cargo semver-checks` into the release workflow

### ISSUE THREAD

**Issue by hlbarber** [smithy-lang/smithy-rs#2565]
The following PRs add semver checks to the CI

https://github.com/awslabs/smithy-rs/pull/2518
https://github.com/awslabs/smithy-rs/pull/2530

This should be integrated into our release workflow to give us some assurance when pushing frequently to release branches.

**Comment by jdisanti** [comment]
I don't think we actually want this since cargo-semver-checks breaks on crate boundaries. This would just end up blocking releases for backwards compatible changes.
