### ISSUE TITLE
In example Makefile, make codegen target depend on the SRC directories

### ISSUE THREAD

**Issue by timClicks** [smithy-lang/smithy-rs#2569]
We currently use a blank rule, which will always run. Spurious compilation can be avoided by adding the source directories as dependencies to the `codegen` target. 

https://github.com/awslabs/smithy-rs/blob/3aa4cc24a5a90a6145beea67596bd09a205f660a/examples/Makefile#L11

**Comment by timClicks** [comment]
In practice, this doesn't cause significant problems because gradle has its own check.

**Comment by jdisanti** [comment]
Closing this as won't fix.
