### ISSUE TITLE
Remove workaround for `tracing-subscriber` missing `regex` features.

### ISSUE THREAD

**Issue by jjant** [smithy-lang/smithy-rs#2619]
Added a workaround for https://github.com/tokio-rs/tracing/issues/2565 in #2618. We should remove that workaround when the mentioned issue is fixed.

These missing features caused tests to fail like this: https://github.com/awslabs/smithy-rs/actions/runs/4763005344/jobs/8465943814.

**Comment by jdisanti** [comment]
Looks like this was done a while ago.
