### ISSUE TITLE
Add tests for interceptor error behavior

### ISSUE THREAD

**Issue by Velfi** [smithy-lang/smithy-rs#2662]
Internal specs for interceptors specify the flow of control in the event of errors. Typically, the spec reads like this:

> Error Behavior : Errors raised by this hook will be stored until all interceptors have had their `beforeExecution()` invoked . Other hooks will then be skipped and execution will jump to `modifyBeforeCompletion` with the raised error as the `InterceptorContext.response()`. If multiple `beforeExecution` methods raise errors, the latest will be used and earlier ones will be logged and dropped.

We store all errors that occur in the `Phase` structures, which also own `InterceptorContext`.

Write tests that ensure all interceptors are getting run and that control flow works as specified for each hook.

**Comment by jdisanti** [comment]
This was implemented a while ago.
