### ISSUE TITLE
Cannot implement IdempotencyTokenProvider due to module privacy

### ISSUE THREAD

**Issue by mcmasn-amzn** [smithy-lang/smithy-rs#2680]
I'm trying to adjust the idempotency token generation (for the sake of integration testing, random tokens are hard to mock.)
However, I can't do it by implementing `IdempotencyTokenProvider` because it is private.

The rust client generator produces a method `make_token` on the config builder. Its parameter accepts a type `impl Into<crate::idempotency_token::IdempotencyTokenProvider>`, but the module `crate::idempotency_token` is private so I can't actually implement `IdempotencyTokenProvider`.

```
error[E0603]: module `idempotency_token` is private
   |
58 | impl dummy_client::idempotency_token::IdempotencyTokenProvider for M...
   |                                            ^^^^^^^^^^^^^^^^^ private module
   |
note: the module `idempotency_token` is defined here
  --> /tmp/dummy-client/src/lib.rs:91:1
   |
91 | mod idempotency_token;
   | ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jdisanti** [comment]
We have `apply_test_defaults` and `with_test_defaults` methods on the Config builder now (behind the `test-utils` feature) that remove randomness from idempotency tokens.

**Comment by mcmasn-amzn** [comment]
@jdisanti awesome, thanks for letting me know!
