### ISSUE TITLE
Modify CI so we are able to cut patch releases off `main` instead of from release branches

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy-rs#2719]
Currently, we always cut patch releases off relase branches. For example, say we tag and release a new minor release, `0.55.0` at commit `R` in branch `main`:

```text
P---R (main, smithy-rs-release-0.55.x)
```

The release process will create a `smithy-rs-release-0.55.x` branch off main with `R` as its base. Any patch releases have to be cut from this branch. So, if we've added non-breaking commits `A`, `B` in `main` since we released:

```text
P---R (smithy-rs-release-0.55.x)---A---B (main)
```

We have to get those commits onto `smithy-rs-release-0.55.x` to release them. That could be done several ways, all of which are problematic.

### 1. Fast-forwarding `smithy-rs-release-0.55.x`

If there haven't been any commits in `smithy-rs-release-0.55.x` that are not in `main`:

```text
P---R (smithy-rs-release-0.55.x)---A---B (main)
```

the `smithy-rs-release-0.55.x` branch could simply be fast-forwarded.

```text
P---R---A---B (main, smithy-rs-release-0.55.x)
```

The problem is the premise is never fulfilled: our CI always adds at least two commits to the release branch (`U1`, `U2` in the below diagrams), to upgrade the smithy-rs runtime crates and to update the changelog. For example, these are the commits for the 0.55.1 release:

* [Upgrade the smithy-rs runtime crates version to 0.55.1](https://github.com/awslabs/smithy-rs/commit/b6ed6488d)
* [Update changelog](https://github.com/awslabs/smithy-rs/commit/a87b41587)

So in reality the graph we start with looks like:

```text
      U1---U2 (smithy-rs-release-0.55.x)
     /
P---R---A---B (main)
```

### 2. Merging `main` into `smithy-rs-release-0.55.x`

This can only be done with a merge commit `M`:

```text
      U1---U2---M (smithy-rs-release-0.55.x)
     /         /
P---R---A-----B (main)
```

The merge should be without conflicts when the changes are easy enough. However, when the branches diverge, things are not as simple. For example, when releasing `0.55.2`, we made the mistake of replaying commits from `main` onto `smithy-rs-release-0.55.x`:

```text
      A---B---U1---U2---C---D---U3---U4 (smithy-rs-release-0.55.x)
     /         
P---R---A---B---C---D---E---F (main)
```

When attempting to release `0.55.3` (`E`, `F`) via a merge, conflicts arose because files were deleted in `main` that had changed in `0.55.2`, and Git stops the merge and asks for a resolution strategy, [even with `--strategy-option theirs`](https://stackoverflow.com/questions/25254037/git-merge-strategy-theirs-is-not-resolving-modify-delete-conflict). See https://github.com/awslabs/smithy-rs/pull/2710.

While replaying things for `0.55.1` and opting to do a merge for `0.55.3` are two different release strategies we should not intermix, _in general we want to retain the ability for the release branch to diverge for arbitrary reasons_, like applying urgent security fixes that may not be needed in `main` for whatever reason. Any divergence will make merging `main` into the release branch prone to merge conflicts. Even when there aren't merge conflicts, Git's three-way-merges can pick incompatible patchsets from the merge sources that result in a broken build; see https://github.com/awslabs/smithy-rs/pull/2710#issuecomment-1553259908 for an example.

### 3. Cherry picking commits from `main` onto `smithy-rs-release-0.55.x`

This is arguably the strategy that works best to reduce human intervention. After doing `git cherry-pick R..origin/main` with the release branch checked out, we should end up with something like:

```text
      U1---U2---A---B (smithy-rs-release-0.55.x)
     /         
P---R---A---B (main)
```

At which point we can begin to release `0.55.1`, which will tack on `U3`, `U4`. Problems come when doing subsequent releases. For example, consider that we want to release `0.55.2`, which has new commits `C`, `D`:

```text
      U1---U2---A---B---U3---U4 (smithy-rs-release-0.55.x)
     /         
P---R---A---B---C---D (main)
```

With `U2` being tagged with `0.55.0` and `U4` tagged with `0.55.1`. Cherry-picking `C`, `D` onto `smithy-rs-release-0.55.x` _almost_ works without human intervention. There are a few problems:

1. There might be commits with identical diffs in both branches. For instance, this happened with https://github.com/awslabs/smithy-rs/pull/2630 (made against `smithy-rs-release-0.55.x`), which was backported to `main` in https://github.com/awslabs/smithy-rs/pull/2636. This was done to quickly get a fix to the release branch to make it non-breaking, that we identified just before releasing, when `main` had already chugged along with breaking changes.
   * So when cherry-picking the `main` commit, Git will halt since the diff is empty, and ask whether we want to cherry pick it anyway with an `--allow-empty` commit, or skip it altogether.
2. There's always at least one conflict in `CHANGELOG.next.toml`. Indeed, after releasing a patch version, we have to empty `CHANGELOG.next.toml` in `main`, since those changes have gone out. See https://github.com/awslabs/smithy-rs/pull/2624 for when we flushed `0.55.2`. This causes a (trivially resolvable) conflict between the commit CI makes to update the changelog in the release branch, and the commit that flushes the changelog in the `main` branch. The operator must handle this conflict regardless.

Additionally, a disadvantage with cherry-picking over merging is that we're replicating Git history. We essentially _double_ all commits from `main` onto the release branch, making Git history longer and less apparent as to what our intention was. It's also more error prone to miss a commit while cherry-picking, and harder to find out if the case happens.

---

## Releasing from `main`

In my opinion, a much easier approach to doing releases is to _always_ cut them off `main`:

```text
         U1---U2 (smithy-rs-release-0.55.0)
        /
       /                       U7---U8 (smithy-rs-release-0.56.0)
      /                       /
     /                       /
P---R---A---B---C---D---X---E (main)
             \       \
              \       \
               \       U5---U6 (smithy-rs-release-0.55.2)
                \
                 U3---U4 (smithy-rs-release-0.55.1)
```

Whenever a breaking change `X` is made to `main`, the next release _must_ be a minor release.

In addition to getting rid of the merge conflicts and cherry-pick issues, this approach has a couple other advantages over the existing approach of cutting patch releases from a release branch:

* The Git history is much simpler: release branches should now _exclusively_ contain the pair of commits done by CI to release (`Ui`, `Uj`), plus any urgent security fixes.
* No PR needs to be made to release.
    - The current approach involves an _unreviewable_ PR with often thousands of LOC changes.
    - With the current approach, the necessity of this PR precludes us from making breaking changes to `tools/` across releases. See https://github.com/awslabs/smithy-rs/pull/2712#issuecomment-1557127325 for a detailed explanation.

**Comment by david-perez** [comment]
I never replied to Harry's comment above. We discussed this and concluded that we're operating under the assumption that we're following our policy of not making breaking changes to `main` in the first few weeks after we cut a minor release. Hotfixes for critical bugs / security vulnerabilities should be developed on the release branch and merged back into `main`. For regular feature work that goes into the next patch release, that should happen on `main` and eventually it will be released in a _new_ branch for that patch release.

**Comment by jdisanti** [comment]
I don't think we can realistically cut patch releases from main since main gets all sorts of non-patch changes added to it. The current release process of merging main into the release branch and cutting seems to be working well.
