### ISSUE TITLE
Port old retry integration tests to the orchestrator standard retry strategy

### ISSUE THREAD

**Issue by Velfi** [smithy-lang/smithy-rs#2743]
[These tests here](https://github.com/smithy-lang/smithy-rs/blob/release-2023-05-23/rust-runtime/aws-smithy-client/src/retry.rs#L407-L614).

**Comment by jdisanti** [comment]
Looks like they were ported over: https://github.com/smithy-lang/smithy-rs/blob/f19a9da9b8f79a7c448246475539c03e1bb58d7e/rust-runtime/aws-smithy-runtime/src/client/retries/strategy/standard.rs#L310
