### ISSUE TITLE
Handle defaults in service config in a uniform manner in the orchestrator

### ISSUE THREAD

**Issue by ysaito1001** [smithy-lang/smithy-rs#2770]
This issue is created based off of [this discussion](https://github.com/awslabs/smithy-rs/pull/2762#pullrequestreview-1477211511). Currently, the generic client checks the absence of key fields in [the builder's build method](https://github.com/awslabs/smithy-rs/blob/main/rust-runtime/aws-smithy-client/src/builder.rs#L393-L421) for the integrity of the client.

When a service config is created all the way from `ConfigLoader`, this usually is not an issue because proper defaults will be provided along the way. But as mentioned above, creating a generic client can run into those missing fields without guardrails. In the orchestrator, we can afford to design a new way to provide proper defaults prior to the execution of the orchestrator.

**Comment by jdisanti** [comment]
I think the way defaults work have been redone since this was filed.
