### ISSUE TITLE
Design/Implement runtime crates versioning strategy

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy-rs#3019]
The Rust SDK needs to have several 1.0 crates—All publicly visible types will be contained with 1.x crates. Other crates will remain at 0.x.

The following crates will go 1.0:
* `aws-smithy-types` & `aws-types`
* `aws-smithy-runtime-api`
* `aws-smithy-async`
* `aws-credential-types`
* `aws-config`: Not re-exported but will be used directly by customers. A 2.0 could be released without causing major breakage.

*All* other runtime crates will remain `0.*`, including `aws-runtime`

The following actions need to be taken:
- [x] #3053
- [x] #3033 
- [x] #3092 
- [x] #3054
- [x] #3043
- [x] Replace usages of `http` with our new `http` abstraction
- [x] #3100
- [x] #3098

Here is the current breakdown:
```toml
allowed_external_types = [
        # OK
        "aws_smithy_types::*",
        "aws_credential_types::*",
        "aws_types::*",
        "aws_smithy_runtime_api::*",
        "aws_smithy_async::*",

        # TODO: Move
        "aws_http::request_id::RequestId", # move to aws-types

        # move to aws_smithy_types
        "aws_smithy_http::result::CreateUnhandledError",
        "aws_smithy_http::result::SdkError",
        # Note: this means SdkBody moves to aws-smithy-types—`http` feature?
        "aws_smithy_http::byte_stream::*",
        "aws_smithy_http::body::SdkBody",
        "aws_smithy_http::operation::error::BuildError",

        # `set_invocation_id_generator` — consider making pub(crate) or moving trait to AwsTypes
        "aws_runtime::invocation_id::SharedInvocationIdGenerator",
        "aws_runtime::invocation_id::InvocationIdGenerator",

        # pending move to runtime-api?
        "aws_smithy_client::http_connector::HttpConnector",

        # delete?
        "aws_smithy_http::endpoint::ResolveEndpoint",
        "aws_smithy_http::endpoint::SharedEndpointResolver",

        # new crate: aws-smithy-event-stream?`
        "aws_smithy_http::event_stream::receiver::Receiver",


        # pending HTTP refactor
        "http::*"
]
```

**Comment by Velfi** [comment]
When we move `SdkBody` we should rename it too. I think having `Sdk` in the name feels wrong for a smithy thing.

**Comment by Velfi** [comment]
`HttpConnector` is being renamed as part of [John's PR](https://github.com/awslabs/smithy-rs/pull/3011/).

**Comment by rcoh** [comment]
> When we move SdkBody we should rename it too. I think having Sdk in the name feels wrong for a smithy thing.
yeah that seems reasonable—although the smithy clients _are_ SDKs in a generic sense so maybe it's not as much of an issue?

**Comment by Velfi** [comment]
also related: https://github.com/awslabs/smithy-rs/issues/3016

**Comment by jdisanti** [comment]
> HttpConnector is being renamed as part of https://github.com/awslabs/smithy-rs/pull/3011/.

Not renamed. HttpClient is something new, and HttpConnector is still around.

**Comment by jdisanti** [comment]
```
        # delete?
        "aws_smithy_http::endpoint::ResolveEndpoint",
        "aws_smithy_http::endpoint::SharedEndpointResolver",
```
Yes. These are the old middleware endpoint resolvers that can be deleted soon.

```
        # pending move to runtime-api?
        "aws_smithy_client::http_connector::HttpConnector",
```
This is dead code that will be deleted.
> Delete or convert aws_smithy_http::ResolveEndpoint into a inlinable (medium change)

I believe it's already replaced by aws-smithy-runtime. If not, then it should be.

```
"aws_smithy_http::result::SdkError",
"aws_smithy_http::body::SdkBody",
```
Are we happy with the `Sdk-` prefix on these names?

```
        # new crate: aws-smithy-event-stream?`
        "aws_smithy_http::event_stream::receiver::Receiver",
```
Why not aws-smithy-runtime-api? Or even aws-smithy-types since this is a part of generated outputs.

```
        # `set_invocation_id_generator` — consider making pub(crate) or moving trait to AwsTypes
        "aws_runtime::invocation_id::SharedInvocationIdGenerator",
        "aws_runtime::invocation_id::InvocationIdGenerator",
```
These should go into aws-runtime-api.

**Comment by ysaito1001** [comment]
> Move SdkBody and bytestream into aws-smithy-types

One implementation wrinkle seems to be `impl http_body::Body for SdkBody`, where `http_body::Body` (from a pre-1.0 crate) is used in public API.
