### ISSUE TITLE
`aws-sigv4` erases prior `Authorization` header values

### ISSUE THREAD

**Issue by nmoutschen** [smithy-lang/smithy-rs#3146]
Hey folks!

I've been exploring an issue with the `aws-sigv4` crate when using AWS VPC Lattice. When trying to send an `Authorization` header, it looks like that crate replaces the original one by using [`HeaderMap.insert`](https://github.com/awslabs/smithy-rs/blob/315d88b6d43832284f48700f6d71d8d402578c23/aws/rust-runtime/aws-sigv4/src/http_request/sign.rs#L170) instead of `.append`.

The former erases all previous values with the same name, while the latter preserves them.

Is this by design for AWS SigV4, or should this be fixed to allow multi-value `Authorization` headers?

**Comment by jdisanti** [comment]
I'm not familiar with AWS VPC Lattice. What is the use-case for multiple authorization headers?

**Comment by nmoutschen** [comment]
> I'm not familiar with AWS VPC Lattice. What is the use-case for multiple authorization headers?

Lattice can use AWS SigV4, and thus the `Authorization` header for [auth policies](https://docs.aws.amazon.com/vpc-lattice/latest/ug/auth-policies.html) to allow traffic to the service network/services, but we have a use-case where some people want to use the `Authorization` header with an end-user identity (e.g. JWT token).

At the moment, we're blocked for these use-cases because the `aws-sigv4` crate erases the previous `Authorization` header value.

That said, there's still an unknown on how Lattice would behave when sending multiple `Authorization` headers. I'm gonna do some tests today and report back.

**Comment by nmoutschen** [comment]
After doing some tests, it looks like AWS VPC Lattice returns a 403 when trying to send two `Authorization` header value.

I haven't tested with other services that allow SigV4 with custom headers/bodies (API Gateway, AppSync, Lambda URLs) if they'd behave the same way, but there might be some internals on how SigV4 signatures are validated that might prevent this from working across the board.
