### ISSUE TITLE
Constant time comparison for SigV4a

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy-rs#3162]
Use constant time bigint here: https://github.com/awslabs/smithy-rs/blob/a69c346001adad00d689a65487c500acd8e85d2a/aws/rust-runtime/aws-sigv4/src/sign/v4a.rs#L69-L74

**Comment by 82marbag** [comment]
In https://github.com/smithy-lang/smithy-rs/pull/3174 I used https://docs.rs/crypto-bigint and checked the functions in use are all constant time. The runtime initialization of the modulus is now a compile time const.
