### ISSUE TITLE
Error struct member with default implementation cause rs clients to fail on build

### ISSUE THREAD

**Issue by codypenta** [smithy-lang/smithy-rs#3182]
When an error member has a default value, it will generate errors with smithy-rs client unless you manually specify `@required`

For example:

```smithy
// Valid Smithy, fails client creation
@error("client")
structure ReservedGroupUsedError {
    message: String = "Cannot use a reserved group name or any variation of"
}
```

```smithy
@error("client")
structure ReservedGroupUsedError {
    @required // This makes the client render again
    message: String = "Cannot use a reserved group name or any variation of"
}
```

I think the code is question is [here](https://github.com/smithy-lang/smithy-rs/blob/1331dc5443e6c3f5494eed2a44606062d3888446/codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/protocol/ProtocolParserGenerator.kt#L163)

I cloned and made this edit below and it worked for me

```kotlin
// If the message member is optional and wasn't set, we set a generic error message.
if (errorMessageMember != null) {
    if (errorMessageMember.isOptional && !errorMessageMember.hasNonNullDefault()) {
        rust(
            """
            if tmp.message.is_none() {
                tmp.message = _error_message;
            }
            """,
        )
    }
}
```

Happy to make a PR if this is the right approach

**Comment by jdisanti** [comment]
To better assess the proposed change, can you provide what the error was before the change?

**Comment by codypenta** [comment]
```rust
            if tmp.message.is_none() {
                tmp.message = _error_message;
            }
```

In the rust code this would throw `is_none()` does not exist on type `String`. And I think there is was some try accessing it as a String but it was an `Option<String>`

**Comment by jdisanti** [comment]
I see. I think the proposed change will fix it in some cases, but potentially not all. To make it work in all cases, the `NullableIndex` must be used to determine if it's wrapped in an Option or not, or better yet, check if the member's symbol is marked as optional (which is determined by the `NullableIndex` earlier in the codegen). Something like:

```kotlin
if (errorMessageMember != null) {
    val symbol = symbolProvider.toSymbol(errorMessageMember)
    if (symbol.is_optional()) {
        ...
```

Feel free to open a PR.
