### ISSUE TITLE
Remove `RustWriter.compileAndTest` in favor of `{client,server}IntegrationTest` or `TestWriterDelegator.compileAndTest`

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy-rs#3193]
Historically we began writing tests using `RustWriter.compileAndTest`, and then we introduced `TestWriterDelegator.compileAndTest` as a newer mechanism which is more powerful and overall nicer to use.

We should remove `RustWriter.compileAndTest` and any dead code paths arising from its removal. In general, when doing so, one should consider refactoring the test to be a `{client,server}IntegrationTest`, which is much simpler to use.

**Comment by david-perez** [comment]
Actually, we think that we should entirely remove `{RustWriter,TestWriterDelegator}.compileAndTest`. Any tests using those should be replaced with `{client,server}IntegrationTest`.

**Comment by david-perez** [comment]
Reverting issue title change. `TestWriterDelegator.compileAndTest` has some benefit in that it doesn't generate a full-blown SDK. While integration tests give more assurances, they contain much more code and take many dependencies, taking longer to compile. There are probably very focused code generators (`EnumGenerator`, `StructureGenerator`...) that may want to test small code snippets using `compileAndTest`.

**Comment by jdisanti** [comment]
I don't think there's any action to be taken here. Going to resolve this.
