### ISSUE TITLE
Reexport http::Uri in aws_config

### ISSUE THREAD

**Issue by pacak** [smithy-lang/smithy-rs#3232]
For `endpoint` method on client buiilder (https://docs.rs/aws-config/0.100.0/aws_config/imds/client/struct.Builder.html#method.endpoint) to work `Uri` must match version used by aws-config - version must be semver compatible to 0.2.

Trying to add `http` dependency with `cargo add http` adds a different version (1.0) and code fails to compile. Adding required version manually is fragile.

A typical solution for such problem is for `aws_config` to reexport `Uri`:

```diff
-use http::Uri;
+pub use http::Uri;
```

**Comment by jdisanti** [comment]
Closing this. See https://github.com/smithy-lang/smithy-rs/pull/3233#issuecomment-1816839602 for explanation.
