### ISSUE TITLE
`impl Display` for generated (string) enums

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy-rs#3336]
`as_str` exists, but we might as well `impl Display` with identical behavior since these are thin string wrappers

**Comment by rcoh** [comment]
If you'd like to take on this issue, the relevant code appears to be here: https://github.com/smithy-lang/smithy-rs/blob/fe36727499a7a74e42a2beca7e76d0b433871181/codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/generators/ClientEnumGenerator.kt#L82

**Comment by iampkmone** [comment]
Will send a PR.
