### ISSUE TITLE
Compilation error: missing base64 dependency

### ISSUE THREAD

**Issue by imp** [smithy-lang/smithy-rs#3356]
When compiled with `RUSTFLAGS="--cfg aws_sdk_unstable"` and

Cargo.toml
```Cargo.toml
[dependencies]
aws-smithy-types = { version = "1.0", features = ["serde-serialize", "serde-deserialize"] }
```
it fails with the following error message

```
error[E0433]: failed to resolve: use of undeclared crate or module `base64`
  --> /xxxxxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-smithy-types-1.1.2/src/blob.rs:45:43
   |
45 |                 serializer.serialize_str(&base64::encode(&self.inner))
   |                                           ^^^^^^ use of undeclared crate or module `base64`
   |
help: consider importing this module
   |
36 +     use crate::base64;
   |
```

It seems that commit f84f9ba8fa43a88f78dae59b8e22a77d436993a5 missed out the change in `mod serde_serialize` alongside that of the `mod serde_deserialize`

**Comment by imp** [comment]
Since the `aws-smithy-types` v1.1.2 is broken without the #3357, (admittedly, not for everyone) is it possible to expedite the new drop of that crate? Alternatively, if releasing the new version is not possible, perhaps 1.1.2 could be yanked meanwhile?

**Comment by rcoh** [comment]
fyi, the unstable feature doesn't do anything currently, work on serde support is in progress. Is there something specific you need that config flag for?
