### ISSUE TITLE
content length enforcement would retroforwardly break tests

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy-rs#3523]
## The problem
this is a "real" semver failure and it's kindof a mind bender: https://github.com/smithy-lang/smithy-rs/actions/runs/8457663420/job/23170159614#step:4:774

A journey:
1. Content length enforcement is implemented via *default runtime plugins*. Default runtime plugins come in directly from the runtime crates. This is a cool emergent property that we can patch runtime behavior of the SDK without even releasing a new version of the SDK.
2. I merged the content length enforcement PR after we cut the release. This caught a lot of tests setting the wrong content length including this one from Dynamo: https://github.com/smithy-lang/smithy-rs/blob/745d48a74e8ffbdb0e39c86ce3db10bdfd6ccf74/aws/sdk/integration-tests/dynamodb/tests/retries-with-client-rate-limiting.rs#L29
3. We are running the tests with the released SDK against the soon-to-be-released runtime libraries. Those tests [have not been updated](https://github.com/awslabs/aws-sdk-rust/blob/main/sdk/dynamodb/tests/retries-with-client-rate-limiting.rs#L28). Those tests fail against the new runtime libraries. 

## The way out
Disable this behavior. Release again to release all the fixed tests. Re-enable this behavior. This issue tracks re-enabling this behavior.

**Comment by ysaito1001** [comment]
Addressed and concluded by the #3618
