### ISSUE TITLE
private type `UploadThroughputCheckFuture` in public interface

### ISSUE THREAD

**Issue by i-mann** [smithy-lang/smithy-rs#3588]
Error found today in trying to build, after a `cargo update` updated use of this library from... I want to say 1.19.x or 1.20.0, to 1.23.0.

Using Rust 1.73.0.

Cargo.toml uses
* aws-config = "1.1"
* aws-sdk-s3 = "1.20"
and Cargo.lock specifies aws-config 1.2.0 and aws-smithy-runtime 1.3.0.

As all the background AWS libraries and dependencies have changed and are maintaining these two versions regardless of a rollback in `Cargo.toml`, it's unclear what I need to roll back to, although it seems like this could be rectified with an appropriately-placed `pub`?

```
Compiling aws-smithy-runtime v1.3.0
error[E0446]: private type `UploadThroughputCheckFuture` in public interface
   --> /home/imann/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-smithy-runtime-1.3.0/src/client/http/body/minimum_throughput.rs:333:1
    |
213 | / pin_project_lite::pin_project! {
214 | |     /// Future that pairs with [`UploadThroughput`] to add a minimum throughput
215 | |     /// requirement to a request upload stream.
216 | |     struct UploadThroughputCheckFuture {
...   |
231 | |     }
232 | | }
    | |_- `UploadThroughputCheckFuture` declared as private
...
333 | / pin_project_lite::pin_project! {
334 | |     #[project = EnumProj]
335 | |     pub(crate) enum MaybeUploadThroughputCheckFuture {
336 | |         Direct { #[pin] future: HttpConnectorFuture },
337 | |         Checked { #[pin] future: UploadThroughputCheckFuture },
338 | |     }
339 | | }
    | |_^ can't leak private type
    |
    = note: this error originates in the macro `$crate::__pin_project_reconstruct` which comes from the expansion of the macro `pin_project_lite::pin_project` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0446]: private type `UploadThroughputCheckFuture` in public interface
   --> /home/imann/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-smithy-runtime-1.3.0/src/client/http/body/minimum_throughput.rs:333:1
    |
213 | / pin_project_lite::pin_project! {
214 | |     /// Future that pairs with [`UploadThroughput`] to add a minimum throughput
215 | |     /// requirement to a request upload stream.
216 | |     struct UploadThroughputCheckFuture {
...   |
231 | |     }
232 | | }
    | |_- `UploadThroughputCheckFuture` declared as private
...
333 | / pin_project_lite::pin_project! {
334 | |     #[project = EnumProj]
335 | |     pub(crate) enum MaybeUploadThroughputCheckFuture {
336 | |         Direct { #[pin] future: HttpConnectorFuture },
337 | |         Checked { #[pin] future: UploadThroughputCheckFuture },
338 | |     }
339 | | }
    | |_^ can't leak private type
    |
    = note: this error originates in the macro `$crate::__pin_project_make_proj_ty` which comes from the expansion of the macro `pin_project_lite::pin_project` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0446`.
error: could not compile `aws-smithy-runtime` (lib) due to 2 previous errors

**Comment by Velfi** [comment]
Hey @i-mann, thanks for submitting this issue. We'll look at this today.

**Comment by ysaito1001** [comment]
Hi @i-mann, can you share with us the output of running the following?
```
rustc --version
```

**Comment by i-mann** [comment]
Hi @ysaito1001 - thank you  - I was on 1.73 and upgrading to 1.77 looks to have resolved it. Do you have any backwards compatibility guarantee that you look to uphold? Just aware that Rust is releasing a minor version almost monthly...!

Thanks for the fast response too @Velfi

**Comment by jdisanti** [comment]
We do. It's stated in the README: https://github.com/awslabs/aws-sdk-rust?tab=readme-ov-file#supported-rust-versions-msrv

Of course, now that I say that and read that section, I realize it's still mentioning "alpha" 😅 It's still correct, however. We currently support two Rust releases prior to the latest (the Rust patch versions are excluded, so if Rust releases 1.80.0, 1.80.1, and 1.80.2, that won't make the minimum supported version 1.80.0).

**Comment by i-mann** [comment]
:facepalm: of course.

Saw your PR - thanks for responding quickly and updating the readme! As background it was a little difficult digging into this as this was a transitive dependency, and I haven't touched Rust and my Rust env for 6 months...! Good to close.

Thanks again.

**Comment by sdroege** [comment]
I also ran into this now. Would it be possible to add the MSRV into the Cargo.toml so this information is directly available instead of having to check if it actually works?

**Comment by jdisanti** [comment]
As a matter of fact, it is: https://github.com/smithy-lang/smithy-rs/pull/3601

Thanks for the suggestion.
