### ISSUE TITLE
`operationShapesThatMustHaveValidationException` does not account for event streaming members.

### ISSUE THREAD

**Issue by drganjoo** [smithy-lang/smithy-rs#3813]
When an operation's input includes an event streaming member, the builder for the operation input or output can raise a `ConstraintViolation` if `build_enforcing_all_constraints` is called and the event streaming member field has not been set.

The `From` implementation that converts `ConstraintViolation` to `RequestRejection` references `ValidationException`. However, if the user has not added `ValidationException` to the errors list, a build-time error is not generated to prompt the user to include `ValidationException`. 

The [operationShapesThatMustHaveValidationException](https://github.com/smithy-lang/smithy-rs/blob/main/codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/ValidateUnsupportedConstraints.kt#L182-L196) method should raise an error in this case.

Here is a sample model:

```smithy
service ConstrainedService {
    operations: [EventStreamsOperation]
}

structure EventStreamsOperationInputOutput {
    @httpPayload
    events: Event,
}

@http(uri: "/event-streams-operation", method: "POST")
operation EventStreamsOperation {
    input: EventStreamsOperationInputOutput,
    output: EventStreamsOperationInputOutput,
}

@streaming
union Event {
    regularMessage: EventStreamRegularMessage,
    errorMessage: EventStreamErrorMessage,
}

structure EventStreamRegularMessage {
    messageContent: String
}

@error("server")
structure EventStreamErrorMessage {
    messageContent: String
}
```

In the operation input builder, `build_enforcing_all_constraints` returns a `ConstraintViolation` if constraints are not met:

```
        fn build_enforcing_all_constraints(
            self,
        ) -> Result<crate::input::EventStreamsOperationInput, ConstraintViolation> {
            Ok(
                crate::input::EventStreamsOperationInput {
                    events: self
                        .events
                        .ok_or(ConstraintViolation::MissingEvents)?,
                },
            )
        }
```

The `From` implementation for converting `ConstraintViolation` to `RequestRejection` uses `crate::error::ValidationException`:

```
    impl ::std::convert::From<ConstraintViolation>
        for ::aws_smithy_http_server::protocol::rpc_v2_cbor::rejection::RequestRejection
    {
        fn from(constraint_violation: ConstraintViolation) -> Self {
            let first_validation_exception_field =
                constraint_violation.as_validation_exception_field("".to_owned());
            let validation_exception = crate::error::ValidationException {
```
The generated Rust code errors out with:

```
error[E0412]: cannot find type `ValidationExceptionField` in module `crate::model`
  --> src/input.rs:78:28
   |
78 |         ) -> crate::model::ValidationExceptionField {
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^ not found in `crate::model`
```

**Comment by david-perez** [comment]
You must always have `ValidationException` in an event streaming operation because the event (the member on the input structure that targets a Smithy `union`/ Rust `enum`) is always required.
