### ISSUE TITLE
expose the Blob contents as a reference

### ISSUE THREAD

**Issue by fommil** [smithy-lang/smithy-rs#3938]
This is how Blob is defined...

```
pub struct Blob {
    inner: Vec<u8>,
}

impl Blob {
   ...
    /// Consumes the `Blob` and returns a `Vec<u8>` with its contents.
    pub fn into_inner(self) -> Vec<u8> {
        self.inner
    }
}

impl AsRef<[u8]> for Blob {
    fn as_ref(&self) -> &[u8] {
        &self.inner
    }
}
```

which means we cannot obtain a `&Vec<u8>` to the inner without cloning the `Blob` (or getting the slice and then making a new Vec, which amounts to the same thing).

Please make a `pub fn inner() -> &Vec<u8>` available so we don't have to copy all this data when optionally processing the contents.

**Comment by Velfi** [comment]
Why is the type of the container important? Isn't a slice enough?

**Comment by fommil** [comment]
to interact with existing apis that take a `&Vec<u8>`. For example, many popular deserialisers.

**Comment by Velfi** [comment]
Apologies for being obstinate, but could you link me an example of a deserializer that expects a `&Vec` instead of a slice?

**Comment by fommil** [comment]
I'm using `prost` to decode KPL aggregated kinesis records, https://docs.rs/prost/latest/prost/

That takes a

```
    fn decode(mut buf: impl Buf) -> Result<Self, DecodeError>
```

where the `impl Buf` is defined in `tokio-rs`... and now that I look even closer I see that there is an implementation for a slice, afterall, that I must have missed the first time around so I've been able to use the `as_ref()` and it works without the memory copy, sorry for the redundant feature request!
