### ISSUE TITLE
Feedback for Generated Code

### ISSUE THREAD

**Issue by davidbarsky** [smithy-lang/smithy-rs#53]
As requested by @rcoh; here are few things I've noticed from reading the documentation.

- `dynamo::model::FailureException` is the only type in the `model` module that represents an error. I think this happened because the underlying Smithy definition might be incorrect.
    - Generally speaking, I don't think that "Exception" shouldn't appear in any Rust code
- The `operation` module is noisy from the builder module [appendix one]. It also hides the actual input operations below the documentation's fold. Unfortunately, applying `#[doc(hidden)]` to a module applies to _all nested modules and exports_, which means that the builder options are hidden: https://github.com/rust-lang/rust/issues/59368
- When documenting input structs, consider using the _operation's_ documentation instead of the input object's documentation [appendix two]. Input structs are the customer's entrypoint to the service, _not_ the operation itself. With a `sans-io` interface, there's no place to document _operations_, which often serve as the _why_ of a service's operation.
- The separate impl blocks for inputs _without_ different generic bounds feel off to me [appendix three]. I'd unify the two.
    -  I'm not sure that an `assemble` associated function is necessary for non-streaming operations, but I believe this relates to the (somewhat) open design question around (de)serialization.
- [Intra-doc links](https://blog.rust-lang.org/inside-rust/2020/09/17/stabilizing-intra-doc-links.html) don't resolve to a URL. You might need to define a `[docs-url]` in the root of each crate: https://github.com/tokio-rs/tracing/pull/1078#discussion_r523787902.
    - Consider using the tokio-rs/tracing repo as an example for documentation configuration. Members of the rustdoc team have use tokio-rs/tracing as a testbed for unstable features.

### Appendix One

<img width="1248" alt="Screen Shot 2020-11-24 at 10 51 36 AM" src="https://user-images.githubusercontent.com/2067774/100117797-2d24b900-2e43-11eb-9883-a014d3383c7c.png">

### Appendix Two

<img width="1248" alt="Screen Shot 2020-11-24 at 10 54 58 AM" src="https://user-images.githubusercontent.com/2067774/100118625-04e98a00-2e44-11eb-8832-970a0d8d786c.png">

### Appendix Three

<img width="1248" alt="Screen Shot 2020-11-24 at 11 06 05 AM" src="https://user-images.githubusercontent.com/2067774/100119631-13847100-2e45-11eb-8372-9318a38ba3e8.png">

**Comment by jdisanti** [comment]
We should take another pass on this feedback before GA. Adding it to the milestone.
