### ISSUE TITLE
Improve middleware customization compiler errors

### ISSUE THREAD

**Issue by jdisanti** [smithy-lang/smithy-rs#634]
Today, we construct our Tower Service by using `ServiceBuilder`, for example:
```rust
        let mut svc = ServiceBuilder::new()
            // Create a new request-scoped policy
            .retry(self.retry_policy.new_request_policy())
            .layer(ParseResponseLayer::<O, Retry>::new())
            // These layers can be considered as occuring in order. That is, first invoke the
            // customer-provided middleware, then dispatch dispatch over the wire.
            .layer(&self.middleware)
            .layer(DispatchLayer::new())
            .service(connector);
```
Problems arise when making changes to existing layers or creating new layers. If the trait bounds on the `impl Service` aren't 100% correct, the compiler error will always be that the `Service` `call` function doesn't exist on the final service since it doesn't actually `impl Service`, and this is difficult to diagnose and solve.

We should experiment with using manual service construction to see if we can get better compiler errors. For example, something like this:
```rust
let svc = RetryService::new(
    ParseResponseService::new(
        custom_middleware(
            DispatchService::new(connector))));
```

We may need to have the same trait bounds on `new` in this case, but perhaps we can write a macro that makes the `impl Service` bounds consistent with `new` to make this less error prone.

**Comment by jdisanti** [comment]
We should determine tower's future plans around layers before making a decision on this.

**Comment by Velfi** [comment]
Closing this since we've decided to remove `tower`
