### ISSUE TITLE
Create trivial access to request IDs for all SDK responses

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy-rs#76]
Request ids are returned in different locations in each protocol (eg. headers, JSON body, XML body etc.).

As an end customer, it should be straightforward to extract that request id from any given response.

- [x] Make it trivial to access the request ID programmatically
- [x] Add a `tracing::debug!` or `tracing::debug_span!` somewhere in the AWS middleware to attach the request ID to logs

**Comment by jdisanti** [comment]
RFC: #2083
