### ISSUE TITLE
Can't consume streaming body using accessor method

### ISSUE THREAD

**Issue by jdisanti** [smithy-lang/smithy-rs#943]
When an operation output has a streaming body (for example, S3 PutObject's `body` field), there's currently no way to consume the contents of that body. For example, this will fail to compile:
```rust
    let result = client
        .get_object()
        .bucket(&bucket_name)
        .key(&test_key)
        .send()
        .await?;

    let payload = result
        .body() // error
        .collect()
        .await?;
```

Error:
```
error[E0507]: cannot move out of a shared reference
  --> src/s3_canary.rs:61:19
   |
61 |       let payload = result
   |  ___________________^
62 | |         .body()
   | |_______________^ move occurs because value has type `ByteStream`, which does not implement the `Copy` trait

```

- [ ] Needs RFC
- [ ] Needs example

Proposal from design meeting:
- leave `.body` as a public member
- `.take_body() -> Option<SdkBody>`

**Comment by guymguym** [comment]
FWIW this works though (using the body member rather than the function)
```
    let payload = result
        .body
        .collect()
        .await?;
```

**Comment by rcoh** [comment]
yeah that's correct. We are planning on removing the body members in most cases because they make it impossible to perform a number of optimizations we may perform in the future around allocations and deserialization

**Comment by 82marbag** [comment]
Are we going for `.take_body() -> Option<SdkBody>`? Can this be worked on?

**Comment by jdisanti** [comment]
The approach we take deserves an RFC, and you're welcome to write one. There may also be other approaches we haven't thought of that might work better than the `take_body` proposal.

**Comment by jdisanti** [comment]
In the end, we exposed both accessor methods and the fields directly, so this isn't a problem anymore.
