### ISSUE TITLE
[Server] Add documentation and example service

### ISSUE THREAD

**Issue by crisidev** [smithy-lang/smithy-rs#951]
Add some good operational documentation to the server README referring to an example service we need to write.

**Comment by tschuett** [comment]
Here is a Amazon maintained not SDK Smithy model:
https://github.com/aws/aws-parallelcluster/tree/develop/api

**Comment by crisidev** [comment]
Oh nice, thanks for pointing this out!

**Comment by guymguym** [comment]
Hi @crisidev 

Is there any example of a server code that uses the codegen-server output? I couldn't find one in the repo.

I also wonder what should be the process of building the codegen-server crate for a given service (S3 in my case) - should I create a build.gradle like in codegen-server-test and use it to generate the code, and then store the generated code in my project?

Thanks!

**Comment by crisidev** [comment]
> Hi @crisidev
> 
> Is there any example of a server code that uses the codegen-server output? I couldn't find one in the repo.

Unfortunately there isn't yet. We have in plans to write an example service with README showcasing all the features, but it has not been done yet. This issue is to keep track of this.

> 
> I also wonder what should be the process of building the codegen-server crate for a given service (S3 in my case) - should I create a build.gradle like in codegen-server-test and use it to generate the code, and then store the generated code in my project?

Yes, you will need a whole gradle setup like in `codegen-server-test`. Also this will be covered by the example sooner or later. If you are in a worry, the repo posted by @tschuett has a model setup. Most of the things you will need are already there, you will have to add the rust-codegen specific that you can find in `codegen-server-test`.

> 
> Thanks!

I am sorry we don't have an example yet, we are at a very early stage of development.

**Comment by guymguym** [comment]
Sure @crisidev I totally understand the stage and trying to contribute to the gaps I can.
Would you consider it relevant to reference to a "living example" to the [s3d project](https://github.com/s3d-rs/s3d) I am building at red hat emerging tech?

**Comment by drganjoo** [comment]
It looks like the s3d project is dormant now, and we don't have any real good open source example to link to. Since we already have the examples folder in this repo we are closing this issue.
