### ISSUE TITLE
Consider adding builder methods for enum variants

### ISSUE THREAD

**Issue by carllerche** [smithy-lang/smithy-rs#991]
Consider setting the [key type](https://docs.rs/aws-sdk-dynamodb/latest/aws_sdk_dynamodb/model/key_schema_element/struct.Builder.html#method.key_type) when creating a Dynamodb table.

I am required to import `KeyType` to pass in `KeyType::Hash` here. An alternative could be to generate builder methods for the enum variants that would let me by pass importing the enum.

Instead of:

```rust
use aws_sdk_dynamodb::model::KeyType;

KeySchemaElement::builder
    .key_type(KeyType::Hash)
    // ...
    .build()
```

It could be:

```rust
KeySchemaElement::builder
    .key_type_hash()
    // ...
    .build()
```

**Comment by jdisanti** [comment]
I like not requiring the import, but this will add a lot more risk of name collisions when code generating the builders. For example, imagine there was a `some` field with an enum that had `OtherThing` as a variant, which should result in `some_other_thing` as the builder method. Then, if the model also had a separate field in the same struct named `some_other_thing`, the code generator would need to decide what to do with that. It gets even trickier if `some_other_thing` is added at a later date, after some releases.
